### ISSUE TITLE
Build an arm64 image

### ISSUE THREAD

**Issue by mvaivre** [opengisch/qgis-docker#73]
First of all, thanks for this image that has been working perfectly fine for me for months ;)

Docker is encouraging image maintainers to provide arm64 images, as many developers are now switching to arm64 platforms (new macs.).

Making this image available for the arm64 platform would make it future proof, and would be awesome.

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by mbernasocchi** [comment]
hey, @mvaivre indeed, it would be great, I've seen that you managed to create one on docker hub, would you care to open a PR so that we can integrate in this image?
Cheers
Marco

**Comment by mbernasocchi** [comment]
@mvaivre are your dockerfiles available somewhere?

**Comment by mvaivre** [comment]
Hey Marco, sorry for missing your previous comment. 

From what I remember, I haven't modified any of your dockerfiles : it's only a "build-step" thing.

If you take a look at the link shared in the first comment, building multi-platform images can be done with a single command with docker's `buildx`, and it's probably what I did.

In order to get this in you CI/CD setup, you would need to adapt your Github Actions build script in order to use `docker buildx` instead of `docker build`.

**Comment by 3nids** [comment]
thanks for the input @mvaivre
